travis:
  secure:
    BINSTAR_TOKEN: FLYLFb9TzdWxjOAUPGgrmV9zKLZSw160gKK1qBAqyv2h093h7Jt74Pii2ot7iuq0ZLndXlsfWUzy+YgAwwnl14HwlYI1zCI+TJq8DKG5+YLszgJWQTjgq4IZmqr5Uj2P0CE+xSW7Qs0XoFW6JzgcW2WJixdkW8THx3vnOiL7PpBDrrG+HgT2tLYxpknY8lJ8G7EIZdtPRNmfaVvUfcNoYjf6Ew17vuTDL9DHLKNEyts/XVr+3v9LtP34/aVzzoC5o4n7Gj7cGt3CvgEK1Rcfww45vsm/8GfYVSp7P0nEgjGDZCqCI4Vl/RS5CGymFN/vSYTBtW6AE2PUUvHltinJKaIJVOgB78U1ZAi4/2LMfS6zdkd665EWwbwseAlmvvayVmlPQimshh3GMP0l5eKerl++gi3ui5ipcT+evf2ZmC+GorOrdAStrZq02APOJgfO/J5t7Qy2vRoOZyQwQ7iyNjtzZqadoHPLbUASDbMINuffukKZOG9JdF0jHe2xce43++keo7q70//Xyke2Rrehlm+0WTlQphUS6u2s569kWO5q8IIFm91gezz2LhX+LgT3+Rlx1vXrfejoKVf99vC16cEy+aipLg756Y6LPUsS7s8uloM1XUAT5cmQFrBPNJyHL9gqvhj5JJ/ampk72X5LgS6XJ7RI5p2M8SFdB201AY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
