travis:
  secure:
    BINSTAR_TOKEN: GjeF9eNnQisfZGDirvaBF+1m5/CNJ8G6LZWRQu1qB04JCJfhwoedat2F9lJqY2W2gyHH6xXD86sOQiL2wE7VpWZcFQMsnhDWxPyf4EnTAN90L6fTR1WsuTqm25Pp2kdm1die4pG1DWiZobOXg3Cr0G4iM3KcC1GCPWyDOTlSRl7Pi8GJB/I087U1txM2/plumWCgQAvRRvWXs009WehQjQK+gDFKSN3WVWeaDqrukX9ZuvkH2FJ83r/n+qSqwK5L4hD3ISk3F9oLW8dxXSInn0VZ5E02iXM7uzTI3Ndj4h78W02yCCOpBBQfq3Hr9rNZrc674vykSFzZtYCfMA/HJtXfQgpn/laPzeuJtm6MNII95KY7waJ9JEcrhGv77tpcIox9gjpB1Iq59pUxphHa3dA5E+MUIUFbQbMzm3RSG4TpXOJiduB1ENg83RRAqXG3g+O9Y0hi3aiPeqre0zLmTl5sl00gHLeeADfYUNstM+C68fuprJf8uXXj6w62TNdjs+T0ER3Madd5MbjQUH1p1A2bg5h+N9zyk9zFTe4qHrqaSRFhV7vFOcoy309InGfSymm4u58oG6kRUNRaY2MAZsDsFO5iGgBTv+cX9k8RrTbu/31jip83NSvRiN+L0lDdvf2FRWN46qHMO/YnZTGzV4kDo6B04Hm1bj8JlrC33XE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
